#!/bin/bash

# 修改maven工程统一版本号

set -e

if [ $# -ne 1 ]
then
  echo "$0 version"
  exit 0
fi

# 回到工程目录
cd `dirname $0`/../
pwd

version=$1
mvn -DnewVersion=${version} -DgenerateBackupPoms=false  versions:set
